# Start from the official PostgreSQL image
FROM postgres:15

# Set environment variables (can be overridden at runtime)
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=secret
ENV POSTGRES_DB=restaurant_db

# Expose the default PostgreSQL port
EXPOSE 3000